### ISSUE TITLE
When installing package from nodejs 14 , a warning message is generated.

### ISSUE THREAD

**Issue by tov324** [stropho/rollup-plugin-banner2#11]
<img width="538" alt="Screen Shot 2021-03-19 at 11 44 05 AM" src="https://user-images.githubusercontent.com/72240999/111724337-6ed0e800-88a8-11eb-9169-3f52693c0685.png">

**Comment by stropho** [comment]
based on the screenshot it is most likely because of npm 7, not node 14 ... Let me not fi the problem still persists after the latest update
