### ISSUE TITLE
banner2(resolveBanner, options) - `options` parameter should be explained in README

### ISSUE THREAD

**Issue by yairEO** [stropho/rollup-plugin-banner2#28]
nothing about the `options` parameter is mentioned

**Comment by stropho** [comment]
Readme mentions the [typescript definition](https://github.com/stropho/rollup-plugin-banner2/blob/master/index.d.ts) file [where you can see](https://github.com/stropho/rollup-plugin-banner2/blob/master/index.d.ts#L20) that you can only pass a boolean value to (not) generate a sourcemap
