### ISSUE TITLE
`banner2` does not add JS comments as a wrapper to every banner

### ISSUE THREAD

**Issue by yairEO** [stropho/rollup-plugin-banner2#29]
please make this optional. this is making me a headache because I am using the same banner text (as a comment) for non-rollup builds of the same project and, the text is added automatically as a comment by those, and I would like to preserve the look, without manually wrapping it with comment `/*` & `*/`:

## I don't want this:

```
rollupBanner(() => `/*${banner}*/\n\n`)
```  

Would be nice to add some option to output a banner automatically as a nicely-formatted comment:

```
/**
 * Tagify v4.20.0 - tags input component
 * By: Yair Even-Or <vsync.design@gmail.com>
 * https://github.com/yairEO/tagify
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 */

rest of code here after a space is automatically added between banner and rest of file contents
```

**Comment by stropho** [comment]
Thanks for the suggestion 😺 
I suppose such formatting could be a simple fn on a few lines, and wouldn't need any external dependency.

Pls propose what would be the new option that would handle the new behaviour. Once we have an agreement, let's create a PR...

**Comment by yairEO** [comment]
`commented: true` I suppose pretty much is self-explanatory, WDYT?

**Comment by stropho** [comment]
I like simple things, but this is too much 😆 Once someone else wants another option, let's say `commentWithNoAsterixOnEveryLine: true`, then there will be bunch of boolean options that kinda depend on each other, have priorities (what overrides what) etc.

Although, there will be only one option now, I would go with something like `bannerFormatting: 'text-to-multiline-comment'` , or `'text-to-jsdoc'` maybe. But it looks very long 😱

**Comment by yairEO** [comment]
This is why I like the options to allow different types of values:

```
commented: true | 'slashes' | 'AsterixEveryLine'
```

And you decide what `true` defaults to

**Comment by stropho** [comment]
@yairEO feel free to review the PR
